### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-meryada#1]
Really cool job @meryada  !!!

Here you have some tips to improve the exercise:

## HTML

- [ ] Be extra careful with syntax, it looks like you have errors when closing As: remember both logo and menu items should be clickables
- [ ] Humanize text in `alt` attributes, a sentence without the dash `-` may do the trick ;)

## CSS - selectors
- [ ] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background color

## CSS - other
- [ ] Finish the main title styles: words are bigger in tablet devices
- [ ] Fix color of links and main title size.

## Good practices
- [ ] Indent and avoid extra white spaces to improve readability and avoid bugs
- [ ] Try to improve your commit messages, better in English and using imperative

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step

Let me know if you have any doubts ;)

Go for it!!

**Comment by meryada** [comment]
Hola Carlos, 

He dejado la corrección en la rama fixing! Espero que esté correcto y no me haya dejado ningún punto sin resolver. 
Un saludo,

**Comment by oneeyedman** [comment]
Está guay, @meryada. Lo doy por suficiente para la evaluación pero mira que en el menú has metido los LI en un A cuando es justo al revés: dentro del LI debe haber un A
